apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-perf
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        bench.tool: fio
    spec:
      restartPolicy: Never
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: etcd-perf
          image: quay.io/cloud-bulldozer/etcd-perf:latest
          volumeMounts:
            - name: etcd-data
              mountPath: /var/lib/etcd
      volumes:
        - name: etcd-data
          persistentVolumeClaim:
            claimName: bench-pvc
