apiVersion: batch/v1
kind: Job
metadata:
  name: etcd-perf-run
  labels:
    bench.tool: fio
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        bench.tool: fio
    spec:
      restartPolicy: Never
      containers:
        - name: etcd-perf
          image: quay.io/cloud-bulldozer/etcd-perf:latest
          volumeMounts:
            - name: etcd-data
              mountPath: /var/lib/etcd
      volumes:
        - name: etcd-data
          persistentVolumeClaim:
            claimName: bench-pvc
