apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bench-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi
  # storageClassName injected by the script
